service: thumbnail-generator
frameworkVersion: '3'

custom:
  stackPrefix: ${self:service}-${self:provider.stage}
  provisionedConcurrency:
    prod: 2
  config: ${file(config/index.js)}
  secrets: 
    cert: ${ssm:/aws/reference/secretsmanager/certificate}

provider:
  name: aws
  runtime: nodejs14.x
  architecture: arm64
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'devevelop'}
  httpApi:
    authorizers:
      customAuthorizer:
        type: request
        functionName: auth
  tags:
    project: thumbnail-generator
  tracing:
    lambda: true
    apiGateway: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - xray:PutTraceSegments
        - xray:PutTelemetryRecords
      Resource: '*'
    
package:
  individually: false
  excludeDevDependencies: true
  patterns:
    - '!.git/**'
    - '!.serverless/**'

functions:
  - ${file(src/authorizer/index.yml)}
  - ${file(src/generator/index.yml)}

resources:
  #S3
  - ${file(resource/s3/originSource.yml)}
  - ${file(resource/s3/resizedSource.yml)}

plugins:
  - serverless-iam-roles-per-function
  - serverless-webpack
  - serverless-offline

