swagger: '2.0'
info:
  description: 'API to upload images and receive them resized'
  version: 1.0.0
  title: Thumbnail Generator
  contact:
    email: agudecima@gmail.com
schemes:
  - https
  - http
paths:
  /upload:
    post:
      tags:
        - Upload Image
      summary: upload an image and resize
      operationId: uploadFile
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - name: image
          in: formData
          description: Image to be resized
          required: true
          type: file
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/200Response'
        '400':
          description: An error has occurred
          schema:
            $ref: '#/definitions/400Response'
      security:
        - thumbnail_auth:
            - write:image
securityDefinitions:
  thumbnail_auth:
    type: oauth2
    authorizationUrl: https://thumbnail.swagger.io/oauth/authorize
    flow: implicit
    scopes:
      write:image: upload image
definitions:
  200Response:
    type: object
    properties:
      message:
        type: string
        example: "Image uploaded, you can see the images in the following links"
      urls:
        type: array
        items:
          type: string
          example: "https://bucket-name.s3.amazonaws.com/image.extension"
  400Response:
    type: object
    properties:
      message:
        type: string
        example: "There was an error getting the file"

